version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
  server:
    container_name: server
    hostname: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    # command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node ./bin/www'
    # networks:
    #   - backend
    environment:
      - PORT_SERVER=8080
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=127.0.0.1
      - COST_JWT=tokencost
      - PHOTO_FOLDER=/images/users
      - TINIFY_KEY=qSy8Bxxm6Zym101zzl643PBFtqVQbTKB
