version: '3.8'
services:
  server:
    container_name: server
    hostname: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    command: sh -c '/bin/wait-for-it.sh db:5432 --timeout=30 -- node ./bin/www'
    depends_on:
      - db
    environment:
      - PORT_SERVER=8080
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=db
      - COST_JWT=tokencost
      - TINIFY_KEY=qSy8Bxxm6Zym101zzl643PBFtqVQbTKB
